### ISSUE TITLE
Starting over with IDE

### ISSUE THREAD

**Issue by sgilbert-student** [cs50/v4-issues#44] opened 2019-08-29 15:14 UTC
#### What symptom did you see (attaching screenshots as necessary)?
I had an interesting problem with one of the students in one class that started this week. She deleted the hidden .c9 folder. I had hoped that when she logged back in it would be recreated, but instead, an Amazon AWS dialog appeared where the only choice was to install Cloud 9 for AWS. When she clicked through, that failed.
To solve the immediate class problem, I had her just create a new GitHub account with a different email address and that worked fine (of course). My question, is, is there any way to abandon the ruined IDE attached to her original GitHub account and start over?

#### When date and time (UTC) did the problem happen?
About 10:15:00 p.m. Tuesday August 27, 2019
#### What steps did you follow to reproduce the problem?
Well, I hesitate to reproduce it because I only have a limited number of github accounts.

#### Which web browser did you use (including version number)?
Latest Chrome

#### Which operating system did you use (including version number)?
Windows 10

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
No, this was a student in our Computer Lab, using her GitHub account.

**Comment by SNathJr** [comment] 2019-08-29 15:38
@sgilbert-student Well, I tried to reproduce the problem by deleting the .c9 folder in the home directory. However, I could not reproduce the same problem, as next time I logged in .c9 folder was created back. Are you sure deletion of .c9 folder is the issue here?

**Comment by SNathJr** [comment] 2019-08-29 15:53
@sgilbert-student @kzidane 

I can confirm that there is an issue here.

**Steps to reproduce:**

1. Delete the .c9 folder
```rm -rf ~/.c9```

2. Reset the IDE / Restart the IDE / Close the tab and log back in
![image](https://user-images.githubusercontent.com/20180524/63955560-88ca9000-caa2-11e9-869b-26ee9f44b293.png)

3. AWS asks if it can install the cloud9 IDE
![image](https://user-images.githubusercontent.com/20180524/63955649-b3b4e400-caa2-11e9-8fad-e5910a126717.png)

![image](https://user-images.githubusercontent.com/20180524/63955675-bf080f80-caa2-11e9-9289-9b972c255533.png)

![image](https://user-images.githubusercontent.com/20180524/63955720-ccbd9500-caa2-11e9-943b-9d67c352cf33.png)

4. It ends up not working and leaves the IDE in a bricked state
![image](https://user-images.githubusercontent.com/20180524/63955975-3f2e7500-caa3-11e9-93d1-81df9783bc33.png)

**Comment by sgilbert-student** [comment] 2020-01-29 04:53
I've just finished setting up for the Spring semester, and again I had a student who deleted the files in the IDE and, essentially, bricked it. It would be nice if there was some kind of "reset" we could use to get a fresh IDE. Currently, the only solution is to create a new GitHub account, and start from there.

**Comment by kzidane** [comment] 2020-02-02 05:14
@sgilbert-student the IDE recovers automatically from this after a few minutes. No need to create a new GitHub account. Unfortunately there's a Cloud9 limitation that's no making protection against this easy but we're looking into solutions.

**Comment by fr33mad** [comment] 2020-05-20 10:27
I am facing the same issue. Please help.

**Comment by fr33mad** [comment] 2020-05-20 10:36
![image](https://user-images.githubusercontent.com/64498258/82436663-c5bf3280-9ac8-11ea-829a-b2019fe4bf77.png)

**Comment by fr33mad** [comment] 2020-05-20 10:37
![image](https://user-images.githubusercontent.com/64498258/82436780-f56e3a80-9ac8-11ea-9d69-648e4ad28b9b.png)

**Comment by kittytanisha** [comment] 2020-06-25 14:41
> 
> 
> @sgilbert-student @kzidane
> 
> I can confirm that there is an issue here.
> 
> **Steps to reproduce:**
> 
>     1. Delete the .c9 folder
>        `rm -rf ~/.c9`
> 
>     2. Reset the IDE / Restart the IDE / Close the tab and log back in
>        ![image](https://user-images.githubusercontent.com/20180524/63955560-88ca9000-caa2-11e9-869b-26ee9f44b293.png)
> 
>     3. AWS asks if it can install the cloud9 IDE
>        ![image](https://user-images.githubusercontent.com/20180524/63955649-b3b4e400-caa2-11e9-8fad-e5910a126717.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/20180524/63955675-bf080f80-caa2-11e9-9289-9b972c255533.png)
> 
> ![image](https://user-images.githubusercontent.com/20180524/63955720-ccbd9500-caa2-11e9-943b-9d67c352cf33.png)
> 
>     1. It ends up not working and leaves the IDE in a bricked state
>        ![image](https://user-images.githubusercontent.com/20180524/63955975-3f2e7500-caa3-11e9-93d1-81df9783bc33.png)

Hi, I have the exact same issue, as the screenshots show. Is this resolved yet?

**Comment by BigTimeStats** [comment] 2020-12-02 08:50
I'm also curious about this as I accidentally moved all files from ~ to another dir, hoping to just move my project files to organize. However, it moved every single file from ~, and when I moved them back they are not hidden anymore. What is a good solution here?

```
mkdir C
find ~ -type f -print0 | xargs -0 mv -t ~/C
find ~/C -type f -print0 | xargs -0 mv -t ~
```
Thank you!

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/29850965/100850224-63ac9600-3438-11eb-93ff-6c6b28a03625.png">

**Comment by anubhavde** [comment] 2020-12-04 18:03
@kzidane Sir i am facing the same problem i accidently deleted the c9 folder which appeared suddenly on my cs50 ide and now when i am opening the cs50 ide it says that aws cloud9 needs a few dependancies etc but repeatedly fails to install the required files. hence i am not able to complete my assignments, please provide any solution for the problem i am currently on my final project on cs50x: Introduction to Computer Science.

**Comment by kzidane** [comment] 2021-01-02 21:14
This should be fixed.

**Closed as completed by kzidane** 2021-01-02 21:14 UTC
