### ISSUE TITLE
CS50 IDE keeps disconnecting and reconnecting every 2-3 seconds

### ISSUE THREAD

**Issue by SNathJr** [cs50/v4-issues#13] opened 2019-04-13 17:37 UTC
#### What symptom did you see (attaching screenshots as necessary)?

CS50 IDE keeps disconnecting and reconnecting every 2-3 seconds.

update: It seems, this problem is specific to my account. If possible, I would like to reset my account and ditch the previous CS50 ide.

![cs50 ide error](https://user-images.githubusercontent.com/20180524/56083299-a6bf8d00-5e40-11e9-9a5c-48b14eeab427.png)

#### When date and time (UTC) did the problem happen?

5:23 pm
Saturday, 13 April 2019
Coordinated Universal Time (UTC)

#### What steps did you follow to reproduce the problem?
1. step 1
![ide cs50 io step 1](https://user-images.githubusercontent.com/20180524/56083169-13d22300-5e3f-11e9-863a-22983e4d2d16.png)

2. step 2
![ide cs50 io error 0](https://user-images.githubusercontent.com/20180524/56083156-e4231b00-5e3e-11e9-96f6-27a7f32f1c9f.png)

3. step 3
![cs50 ide error](https://user-images.githubusercontent.com/20180524/56083299-a6bf8d00-5e40-11e9-9a5c-48b14eeab427.png)

#### Which web browser did you use (including version number)?

Chrome (latest)

#### Which operating system did you use (including version number)?

Windows 10

#### Did you log in to CS50 IDE using the same GitHub account you used to create this issue?
Yes

#### Additional info: 

I tried to reset settings in ide menu to no avail. The problem still persists.

I even tried revoking authorization from github and re-authorizing, still no avail.

Prior to this error, I was trying to enable .bashrc in my home directory.

**Comment by SNathJr** [comment] 2019-04-13 20:01
So, it seems I fixed this error. I tried opening the ide with https://ide.cs50.io/?reset=state

P.S: I would still very much like to know how to delete the CS50 ide and create another

**Comment by kzidane** [comment] 2019-04-22 14:57
From the error, it seems to me that the debugger plugin wasn't able to write the debugger's interface to disk for some reason, but I'm not quite sure why this would happen or why it would be fixed by resetting the state. I'm gonna close this issue for now since you managed to fix, but please feel free to comment or open a new issue if you found a way to reproduce so that we can track down and fix.

Re you other question, unfortunately deleting workspaces and creating new ones isn't supported yet in the beta IDE.

**Closed as completed by kzidane** 2019-04-22 14:57 UTC
